version: "3"

services:
  app:
    build: .
    restart: "always"
    ports:
      - "${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}"
    volumes:
      - ".:/src/github.com/voyage-finance/voyage-tg-server"
    networks:
      - "bot_network"
    command: "go run main.go"

networks:
  bot_network:
    external:
      name: "${NETWORK_NAME}"
