name: Deploy to remote server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to remote server via SSH
        uses: appleboy/ssh-action@master
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          script: |
            cd voyage/bundler
            git pull
            make run_bundler_staging_daemon
